runtime: php83
env: flex

runtime_config:
    document_root: public

skip_files:
    - .env

resources:
    cpu: 2
    memory_gb: 4
    disk_size_gb: 100

env_variables:
    APP_NAME: "FABLMS"
    APP_ENV: "production"
    APP_DEBUG : "true"
    APP_KEY: "base64:GX5hK6lFJLwYSihnHIwBEW5cxG9ZAEDWEqNRiry5Cpg="
    SESSION_DRIVER: "file"

    APP_LOG: "daily"
    APP_TIMEZONE: "America/Los_Angeles"
    APP_LOCALE: "en"
    APP_FALLBACK_LOCALE: "en"
    APP_FAKER_LOCALE: "en_US"
