name: laravel
services:
  mailpit:
    image: 'axllent/mailpit:latest'
    container_name: mailpit
    ports:
      - '1025:1025'
      - '8025:8025'
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  meilisearch:
    image: 'getmeili/meilisearch:latest'
    container_name: meilisearch
    user: "33:1000"
    ports:
      - "7700:7700"
    environment:
      - MEILISEARCH_KEY
      - TZ
    volumes:
      - ./storage/framework/meilisearch:/meili_data
  mariadb:
    image: mariadb:latest
    container_name: db
    user: "33:1000"
    ports:
      - '3306:3306'
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD:-laravel_root}
      - MARIADB_USER=${DB_USERNAME:-laravel}
      - MARIADB_PASSWORD=${DB_PASSWORD:-laravel}
      - MARIADB_DATABASE=${DB_DATABASE:-laravel}
      - TZ
    volumes:
      - ./storage/framework/db:/var/lib/mysql
  valkey:
    image: valkey/valkey:latest
    container_name: redis
    ports:
      - '6379:6379'
    user: "33:1000"
    environment:
      - TZ
    volumes:
      - ./storage/framework/redis:/data
    command: valkey-server --requirepass ${REDIS_PASSWORD:-laravel}