<?php

namespace App\Mcp\Tools;

use Illuminate\JsonSchema\JsonSchema;
use Laravel\Mcp\Request;
use Laravel\Mcp\Response;
use Laravel\Mcp\Server\Tool;

class GetRubricTool extends Tool
{
	protected string $name = 'get-rubric';
	protected string $title = 'Get Skill Rubric';
	/**
	 * The tool's description.
	 */
	protected string $description = <<<'MARKDOWN'
        This tool gets the rubric that is associated with a skill in the system. The rubric is a 
        a table with the rows representing the criteria and the columns representing the the performance 
        ratings. The criteria describe what will be assessed in the Skill. The performance ratings 
        are the possible scores that the Skill can receive, always starting at 0.  Each cell in the table
        describes what is the minimum that the student must demonstrate in that criteria to receive the 
        corresponding performance rating.
    MARKDOWN;

    /**
     * Handle the tool request.
     */
    public function handle(Request $request): Response
    {
        //

        return Response::text('The content generated by the tool.');
    }

    /**
     * Get the tool's input schema.
     *
     * @return array<string, \Illuminate\JsonSchema\JsonSchema>
     */
    public function schema(JsonSchema $schema): array
    {
	    return
		    [
			    'id' => $schema->integer()->description('The ID of the skill to get the rubric for.')->required(),
		    ];
    }
}
